# Generated by Django 5.2.3 on 2025-06-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
