# Generated by Django 5.2.3 on 2025-06-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_car_alter_team_photo_booking_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(choices=[('aeroporto', 'Aeroporto'), ('ufficio', 'Ufficio'), ('port', 'Porto')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
