# Generated by Django 5.2.3 on 2025-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Benzina', 'Benzina'), ('elettrico', 'Elettrico'), ('ibrido', 'Ibrido')], max_length=10),
        ),
    ]
