# Generated by Django 5.2.3 on 2025-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Benzina', 'Benzina'), ('Elettrico', 'Elettrico'), ('Ibrido', 'Ibrido')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('Manuale', 'Manuale'), ('Automatico', 'Automatico')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(choices=[('Aeroporto', 'Aeroporto'), ('Ufficio', 'Ufficio'), ('Port', 'Porto')], max_length=10),
        ),
    ]
