# Generated by Django 5.2.3 on 2025-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_car_fuel_type_alter_car_gearbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
    ]
