# Generated by Django 5.2.1 on 2025-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_booking_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
