# Generated by Django 5.2.3 on 2025-07-03 23:52

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_principal',
            field=models.ImageField(null=True, upload_to=cars.models.car_image_upload_to),
        ),
    ]
