# Generated by Django 5.2.1 on 2025-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_principal',
            field=models.ImageField(upload_to='cars/{{ car.model }}/'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/{{ car.model }}/secondary/'),
        ),
    ]
