# Generated by Django 5.2.1 on 2025-06-16 10:57

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_image_principal_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_principal',
            field=models.ImageField(upload_to=cars.models.car_image_upload_to),
        ),
    ]
