# Generated by Django 5.2.3 on 2025-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_image_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
