# Generated by Django 5.2.1 on 2025-06-16 11:00

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_image_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to=cars.models.car_secondary_image_upload_to),
        ),
    ]
